<?xml version="1.0" encoding="utf-8"?><Database Name="dbproyectolenguajes" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=proyectolenguajesfinal.database.windows.net;Initial Catalog=dbproyectolenguajes;User ID=kevintc;Connect Timeout=60;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="dbproyectolenguajesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pedido" Member="Pedido">
    <Type Name="Pedido">
      <Column Name="PedidoID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaPedido" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EstadoPedidoID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Pedido_X_Plato" Member="Pedido_X_Plato" ThisKey="PedidoID" OtherKey="PedidoID" Type="Pedido_X_Plato" />
      <Association Name="Usuario_Pedido" Member="Usuario" ThisKey="UsuarioID" OtherKey="UsuarioID" Type="Usuario" IsForeignKey="true" />
      <Association Name="EstadoPedido_Pedido" Member="EstadoPedido" ThisKey="EstadoPedidoID" OtherKey="EstadoPedidoID" Type="EstadoPedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoUsuario" Member="TipoUsuario">
    <Type Name="TipoUsuario">
      <Column Name="TipoUsuarioID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescTipoUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TipoUsuario_Usuario" Member="Usuario" ThisKey="TipoUsuarioID" OtherKey="TipoUsuarioID" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="UsuarioID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CorreoElectronico" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NombreCompleto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Bloqueado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TipoUsuarioID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DescUsuario" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ActivoSN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Pedido" Member="Pedido" ThisKey="UsuarioID" OtherKey="UsuarioID" Type="Pedido" />
      <Association Name="TipoUsuario_Usuario" Member="TipoUsuario" ThisKey="TipoUsuarioID" OtherKey="TipoUsuarioID" Type="TipoUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Plato" Member="Plato">
    <Type Name="Plato">
      <Column Name="PlatoID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DescPlato" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ActivoSN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Plato_Pedido_X_Plato" Member="Pedido_X_Plato" ThisKey="PlatoID" OtherKey="PlatoID" Type="Pedido_X_Plato" />
    </Type>
  </Table>
  <Table Name="dbo.Pedido_X_Plato" Member="Pedido_X_Plato">
    <Type Name="Pedido_X_Plato">
      <Column Name="PlatoID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PedidoID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CantidadPlato" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PedidoXPlatoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Pedido_Pedido_X_Plato" Member="Pedido" ThisKey="PedidoID" OtherKey="PedidoID" Type="Pedido" IsForeignKey="true" />
      <Association Name="Plato_Pedido_X_Plato" Member="Plato" ThisKey="PlatoID" OtherKey="PlatoID" Type="Plato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EstadoPedido" Member="EstadoPedido">
    <Type Name="EstadoPedido">
      <Column Name="EstadoPedidoID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DescEstadoPedido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TiempoCambioEstado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="EstadoPedido_Pedido" Member="Pedido" ThisKey="EstadoPedidoID" OtherKey="EstadoPedidoID" Type="Pedido" />
    </Type>
  </Table>
</Database>